# Generated by Django 5.2.7 on 2025-10-06 19:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_competitor_team_car_competitor_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('rally', 'Rally'), ('hill_climb', 'Hill Climb'), ('autocross', 'Autocross'), ('karting', 'Karting')], max_length=50)),
                ('dorsal', models.CharField(max_length=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='events.car')),
                ('codriver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codriver_inscriptions', to='events.competitor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_inscriptions', to='events.competitor')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='events.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='events.team')),
            ],
        ),
    ]
