runtime: python311

entrypoint: gunicorn -b :$PORT backend.wsgi:application

instance_class: F1  # clase m치s peque침a y gratuita

automatic_scaling:
  max_instances: 1    # m치ximo 1 instancia (gratis)
  min_instances: 0    # no mantiene instancias cuando no hay tr치fico
  max_idle_instances: 1
  min_idle_instances: 0
  target_cpu_utilization: 0.9
  target_throughput_utilization: 0.9

env_variables:
  DJANGO_SETTINGS_MODULE: "backend.settings"

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto