# Generated by Django 5.2.7 on 2026-08-16 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('category', models.CharField(choices=[('rally', 'Rally'), ('hill_climb', 'Hill Climb'), ('autocross', 'Autocross'), ('karting', 'Karting')], max_length=50)),
                ('provider', models.CharField(choices=[('kronobot', 'Kronobot'), ('kronolive', 'Kronolive'), ('other', 'Other')], max_length=50)),
                ('status', models.BooleanField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events')),
                ('provider_inscriptions_url', models.URLField(blank=True, null=True)),
                ('provider_event_url', models.URLField(blank=True, null=True)),
                ('provider_times_url', models.URLField(blank=True, null=True)),
                ('provider_stages_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=150)),
                ('group', models.CharField(max_length=150)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='inventory.competitor')),
            ],
        ),
        migrations.CreateModel(
            name='EventStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('loop', models.CharField(max_length=5)),
                ('loop_position', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('distance_km', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('finished', 'Finished')], max_length=20)),
                ('finished_count', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='inventory.event')),
            ],
            options={
                'unique_together': {('event', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('regularity', 'Regularity'), ('regularity_sport', 'Regularity Sport'), ('solo', 'Solo'), ('with_codriver', 'With Codriver'), ('single_sport_regularity', 'Single Sport Regularity'), ('drift', 'Drift')], max_length=50)),
                ('dorsal', models.CharField(max_length=10)),
                ('total_seconds', models.FloatField(blank=True, null=True)),
                ('total_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_penalty_seconds', models.FloatField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='inventory.car')),
                ('codriver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codriver_inscriptions', to='inventory.competitor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_inscriptions', to='inventory.competitor')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='inventory.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='inventory.team')),
            ],
        ),
        migrations.AddField(
            model_name='competitor',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competitors', to='inventory.team'),
        ),
        migrations.CreateModel(
            name='StageResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('value_seconds', models.FloatField()),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('event_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_results', to='inventory.eventstage')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_results', to='inventory.inscription')),
            ],
            options={
                'unique_together': {('inscription', 'event_stage')},
            },
        ),
    ]
