# Generated by Django 5.2.7 on 2026-08-16 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('debug', 'Debug')], max_length=20)),
                ('name', models.CharField(choices=[('stage_time_imported', 'Stage Time Imported'), ('event_synced', 'Event Synced'), ('inscriptions_imported', 'Inscriptions Imported')], max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_tasks', to='inventory.event')),
            ],
        ),
    ]
