# Generated by Django 5.2.7 on 2026-08-18 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_competitor_team_name_normalized'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTimelineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('stage_finished', 'Stage Finished'), ('abandonment', 'Abandonment'), ('did_not_start', 'Did Not Start'), ('scratch', 'Scratch'), ('stage_completed', 'Stage Completed')], max_length=30)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_items', to='inventory.event')),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_items', to='inventory.inscription')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_items', to='inventory.eventstage')),
            ],
        ),
    ]
